Author: Shankar J  
Website: https://shankar-jayaraj.github.io/  
LinkedIn: https://www.linkedin.com/in/drshankarj  
Licensed under CC BY-NC-SA 4.0. 

##  vector operations using NumPy

In [44]:
import numpy as np

# Create vectors
v1 = np.array([3, 4])
v2 = np.array([1, 2])
print(v1)  # [3, 4]
print(v2)  # [1, 2]

[3 4]
[1 2]


In [45]:

# Vector addition
v_sum = v1 + v2  # [4, 6]
print(v_sum)


[4 6]


In [46]:


# Scalar multiplication
v_scaled = 2 * v1  # [6, 8]

print(v1)

print(v_scaled)  # [6, 8]


[3 4]
[6 8]


In [50]:

# Calculate norms
l1_norm = np.sum(np.abs(v1))  # 7
l2_norm = np.linalg.norm(v1)  # 5.0
linf_norm = np.max(np.abs(v1))  # 4
print(f'L1 norm:{l1_norm}')  # 7
print(f'L2 norm:{l2_norm}')  # 5.0
print(f'L∞ norm:{linf_norm}')  # 4

L1 norm:7
L2 norm:5.0
L∞ norm:4


In [51]:

# Dot product
dot_product = np.dot(v1, v2)  # 11
print(f'Dot Product: {dot_product}')  # 11

Dot Product: 11


In [53]:


# Check orthogonality
u1 = np.array([1, 0])
u2 = np.array([0, 1])
print(f'Dot Product: {np.dot(u1, u2)}')  # 0 (orthogonal)


Dot Product: 0


## Matrix operations in NumPy

In [55]:
import numpy as np

# Create matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(f'A:\n{A}')  # [[1, 2], [3, 4]]
print(f'B:\n{B}')  # [[5, 6], [7, 8]]

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]


In [57]:
# Matrix addition
C = A + B  # [[6, 8], [10, 12]]
print(f'C (A + B):\n{C}')  # [[6, 8], [10, 12]]

C (A + B):
[[ 6  8]
 [10 12]]


In [58]:
# Matrix multiplication
D = A @ B  # [[19, 22], [43, 50]]
print(f'D (A @ B):\n{D}')  # [[19, 22], [43, 50]]

D (A @ B):
[[19 22]
 [43 50]]


In [59]:
# Transpose
A_T = A.T  # [[1, 3], [2, 4]]
print(f'A Transpose:\n{A_T}')  # [[1, 3], [2, 4]]

A Transpose:
[[1 3]
 [2 4]]


In [60]:
# Check rank
rank = np.linalg.matrix_rank(A)
print(f'Rank of A: {rank}')  # 2 (full rank for 2x2 matrix)

Rank of A: 2
