In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.linalg import svd, eig
import seaborn as sns

## 8. Assessment and Practice Problems

### Problem 1: Compute SVD manually for the matrix:

In [ ]:
print("Practice Problems:")
print("="*50)

# Problem 1: Manual SVD calculation
print("Problem 1: Compute SVD manually for the matrix:")
test_matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(test_matrix)


Practice Problems:
Problem 1: Compute SVD manually for the matrix:
[[1 2]
 [3 4]
 [5 6]]


In [3]:

# Solution framework
print("\nSolution steps:")
print("1. Compute A^T * A")
AtA_test = test_matrix.T @ test_matrix
print(f"A^T * A = \n{AtA_test}")

print("2. Find eigenvalues and eigenvectors of A^T * A")
eigenvals_test, V_test = np.linalg.eigh(AtA_test)
print(f"Eigenvalues: {eigenvals_test}")



Solution steps:
1. Compute A^T * A
A^T * A = 
[[35 44]
 [44 56]]
2. Find eigenvalues and eigenvectors of A^T * A
Eigenvalues: [ 0.26450509 90.73549491]


# Problem 2: PCA interpretation

In [5]:


print("\n" + "="*50)
print("Problem 2: Data interpretation")

# Generate interpretable dataset
np.random.seed(123)
heights = np.random.normal(170, 10, 100)  # Heights in cm
weights = 0.8 * heights + np.random.normal(0, 5, 100)  # Correlated weights
ages = np.random.normal(25, 5, 100)  # Independent ages

dataset = np.column_stack([heights, weights, ages])
dataset_centered = dataset - np.mean(dataset, axis=0)


print("Dataset: [Height, Weight, Age]")
print(dataset_centered)
print(f'Dataset shape: {dataset_centered.shape}')



Problem 2: Data interpretation
Dataset: [Height, Weight, Age]
[[-1.11273968e+01 -5.59396616e+00  3.99220715e+00]
 [ 9.70236373e+00 -2.02987086e+00 -2.51487010e+00]
 [ 2.55869425e+00  5.70595638e+00  1.14791671e+01]
 [-1.53340379e+01  8.21967147e-01  3.91714121e+00]
 [-6.05709325e+00 -4.87112670e+00  4.44120302e-01]
 [ 1.62432746e+01  1.32630082e+01 -5.57654960e-01]
 [-2.45378832e+01 -1.86348813e+01  4.30451243e-02]
 [-4.56021702e+00 -1.28603744e+01 -4.10087879e+00]
 [ 1.23882719e+01  1.21390285e+01 -3.56140093e-04]
 [-8.93849476e+00 -1.50801667e+01  1.86907414e+00]
 [-7.05995225e+00 -7.68868198e+00  3.37336463e+00]
 [-1.21818042e+00  5.33748122e+00  3.37410545e+00]
 [ 1.46428055e+01  8.13583745e+00 -8.98731177e-01]
 [-6.66011070e+00 -2.72416580e+00 -6.60475471e+00]
 [-4.71091033e+00  1.39264481e+00 -2.86985657e+00]
 [-4.61460349e+00 -2.20030070e+00  8.53662177e+00]
 [ 2.17882101e+01  1.06735035e+01  4.95594812e+00]
 [ 2.15967702e+01  1.57127176e+01  2.32375449e+00]
 [ 9.76944824e+00  