In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.linalg import svd, eig
import seaborn as sns

### Assessment and Practice Problems

In [25]:
import numpy as np

# Define the matrix
test_matrix = np.array([[1, 2], [3, 4], [5, 6]])
print("Original matrix A:")
print(test_matrix)

Original matrix A:
[[1 2]
 [3 4]
 [5 6]]


In [26]:
# Step 2: Compute eigenvalues and eigenvectors of A^T * A
eigenvals, V = np.linalg.eigh(AtA)
print("\n2. Eigenvalues of A^T * A:")
print(eigenvals)
print("Eigenvectors of A^T * A:")
print(V)


2. Eigenvalues of A^T * A:
[ 0.26450509 90.73549491]
Eigenvectors of A^T * A:
[[-0.78489445  0.61962948]
 [ 0.61962948  0.78489445]]


In [27]:
# Step 3: Sort eigenvalues/eigenvectors in descending order
idx = eigenvals.argsort()[::-1]
eigenvals_sorted = eigenvals[idx]
V_sorted = V[:, idx]

# Step 4: Compute singular values (σ = sqrt(λ))
singular_values = np.sqrt(eigenvals_sorted)
print("\n3. Singular values (σ):")
print(singular_values)


3. Singular values (σ):
[9.52551809 0.51430058]


In [28]:

# Step 5: Construct Σ matrix
Sigma = np.zeros(test_matrix.shape)
np.fill_diagonal(Sigma, singular_values)
print("\n4. Sigma matrix (Σ):")
print(Sigma)


4. Sigma matrix (Σ):
[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


In [29]:
# Step 6: Compute U using U = A * V * Σ⁻¹
U_columns = []
for i in range(len(singular_values)):
    if not np.isclose(singular_values[i], 0):
        u_col = (test_matrix @ V_sorted[:, i]) / singular_values[i]
        U_columns.append(u_col)

# Add orthogonal vector for null space
U = np.column_stack(U_columns)
cross_product = np.cross(U[:,0], U[:,1])
U = np.column_stack((U, cross_product / np.linalg.norm(cross_product)))

print("\n5. Matrix U:")
print(U)


5. Matrix U:
[[ 0.2298477   0.88346102 -0.40824829]
 [ 0.52474482  0.24078249  0.81649658]
 [ 0.81964194 -0.40189603 -0.40824829]]


In [30]:
# Step 7: Verify reconstruction
A_reconstructed = U @ Sigma @ V_sorted.T
print("\n6. Reconstructed A = U * Σ * V^T:")
print(A_reconstructed)
print("\nReconstruction error:", np.linalg.norm(test_matrix - A_reconstructed))


6. Reconstructed A = U * Σ * V^T:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

Reconstruction error: 1.0877919644084146e-15
